/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ist.voice.req.org.form;

import com.ist.voice.req.org.model.LoginModel;
import com.ist.voice.req.org.util.Function;
import java.io.IOException;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mhc
 */
public class UserProfile extends javax.swing.JFrame {

    Function siteFunction = new Function();

    /**
     * Creates new form UserProfile
     */

    public UserProfile() throws IOException {

        if (!siteFunction.isLogin()) {
            gotoLoginpage();
        }
        initComponents();

        LoginModel loginModel = siteFunction.getUserByID();
        if (!loginModel.isError()) {
            text_name.setText(loginModel.getResult().getName());
            text_email.setText(loginModel.getResult().getEmail());
            text_phone.setText(loginModel.getResult().getPhone());
        }
    }

    private void gotoLoginpage() {

        dispose();
        Login login = new Login();
        login.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        text_name = new javax.swing.JTextField();
        text_email = new javax.swing.JTextField();
        text_phone = new javax.swing.JTextField();
        text_re_password = new javax.swing.JPasswordField();
        text_password = new javax.swing.JPasswordField();
        updateUserProfileButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        leftSideMenu = new javax.swing.JMenu();
        menuRecord = new javax.swing.JMenuItem();
        menuItemRecognitionList = new javax.swing.JMenuItem();
        menu_profile = new javax.swing.JMenuItem();
        menu_user_signOut = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Name:");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Email:");
        jLabel2.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Phone:");
        jLabel3.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Password:");
        jLabel4.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Re-Password:");
        jLabel5.setBorder(new javax.swing.border.MatteBorder(null));

        updateUserProfileButton.setBackground(new java.awt.Color(153, 0, 0));
        updateUserProfileButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updateUserProfileButton.setForeground(new java.awt.Color(255, 255, 255));
        updateUserProfileButton.setText("UPDATE");
        updateUserProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUserProfileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_name)
                    .addComponent(text_email, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(text_phone, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(text_password)
                    .addComponent(text_re_password)
                    .addComponent(updateUserProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 933, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(text_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(text_re_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateUserProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(325, Short.MAX_VALUE))
        );

        leftSideMenu.setText("Menu");

        menuRecord.setText("Record");
        menuRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRecordActionPerformed(evt);
            }
        });
        leftSideMenu.add(menuRecord);

        menuItemRecognitionList.setText("Recognition List");
        menuItemRecognitionList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRecognitionListActionPerformed(evt);
            }
        });
        leftSideMenu.add(menuItemRecognitionList);

        menu_profile.setText("Profile");
        menu_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_profileActionPerformed(evt);
            }
        });
        leftSideMenu.add(menu_profile);

        menu_user_signOut.setText("Signout");
        menu_user_signOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_user_signOutActionPerformed(evt);
            }
        });
        leftSideMenu.add(menu_user_signOut);

        jMenuBar1.add(leftSideMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemRecognitionListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRecognitionListActionPerformed
        // TODO add your handling code here:
        dispose();
        try {
            new RecognitionList().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(UserProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemRecognitionListActionPerformed

    private void menu_user_signOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_user_signOutActionPerformed
        // TODO add your handling code here:
        siteFunction.unsetLoginData();
        gotoLoginpage();

    }//GEN-LAST:event_menu_user_signOutActionPerformed

    private void updateUserProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateUserProfileButtonActionPerformed
        String email=text_email.getText();
        String name=text_name.getText();
        String phone=text_phone.getText();
        String password=text_password.getText();
        String rePassword=text_re_password.getText();
        if(!siteFunction.validateEmailAddress(email)){
            siteFunction.showAlertMessage("Invalid email address");
        }else{        
            if(!password.isEmpty() &&!password.equals(rePassword)){
            siteFunction.showAlertMessage("re-password is not matched");
            }else{
            if(password.isEmpty())
                password=null;
                try {
                    LoginModel response=siteFunction.updateUser(email, password, name, phone);
                    siteFunction.showAlertMessage(response.getMessage());
                } catch (IOException ex) {
                    Logger.getLogger(UserProfile.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
        
    }//GEN-LAST:event_updateUserProfileButtonActionPerformed

    private void menu_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_profileActionPerformed
       dispose();
        try {
            new UserProfile().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(UserProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menu_profileActionPerformed

    private void menuRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRecordActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            dispose();
            new VoiceRecording().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(RecognitionList.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuRecordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new UserProfile().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(UserProfile.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu leftSideMenu;
    private javax.swing.JMenuItem menuItemRecognitionList;
    private javax.swing.JMenuItem menuRecord;
    private javax.swing.JMenuItem menu_profile;
    private javax.swing.JMenuItem menu_user_signOut;
    private javax.swing.JTextField text_email;
    private javax.swing.JTextField text_name;
    private javax.swing.JPasswordField text_password;
    private javax.swing.JTextField text_phone;
    private javax.swing.JPasswordField text_re_password;
    private javax.swing.JButton updateUserProfileButton;
    // End of variables declaration//GEN-END:variables
}
